name: "build"
on: pull_request

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup node
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: |
          npm install

      - name: Prettier & ESLint
        run: |
          npm run fix:prettier && npm run fix:eslint

      - name: TSC & Vite build
        run: |
          npm run build
